
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ProjetInstag_development

test:
  <<: *default
  database: ProjetInstag_test

production:
  <<: *default
  database: ProjetInstag_production
  username: ProjetInstag
  password: <%= ENV['PROJETINSTAG_DATABASE_PASSWORD'] %>
